### ISSUE TITLE
Filter dropdown iis extremely confusing

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#80] opened 2015-06-13 08:02 UTC
I started writing a different issue, and in the middle understood what was going on...

The options in the dropdown are to filter 'All', 'Selected' or 'Not Selected'.
The checkbox in this case is just an icon - but I thought it was actually a checkbox!
My initial issue was that it wasn't working because 'Selected' always appears chosen.

The icons were adopted from gmail but with a different meaning. VERY CONFUSING.

Until we find a better representation - we should just show the text (All/Selected/Not Selected)

**Comment by assafharel** [comment] 2015-06-14 10:31
From my experience, after the first confusion, you get used to it fast, and then it's very usable. Let's discuss first before assigning to Pavel.

**Comment by Pavek** [comment] 2015-07-01 18:12
I agree with that. Also it has some not-nice behavior when coupled with show less/more feature which was implemented as an after-thought.

Now I see that Global vs Local items are quite differet in nature and should not be displayed in the same table:
Global:
 - needs show more/less behavior (because list may be huge)
 - can be searched to reveal items not displayed or even loaded yet
 - do not have edit/delete/must-have options (read-only by design)
 - the most importan operation is: choose items and move the to selected(local) list (I believe it should be 2 steps as in Gmail)

Local (including newly added aka custom):
- don't need show more/less & search
- are editable (Description, must-have etc)
- can be unselected - which removes them from decision table but not from the local list (because otherwise new(custom) items will be lost forever)
- can be deleted - which removes from the list and all custom data is lost forever

So, the proposal is:
- remove filter dropdown
- have 2 tables -- similar to original design of Assaf -- but to make it responsive I propose to show them in **2 tabs**.
- **1st tab** shows Global items + Search
 - user searches (optionally) and *selects* items first, then *moves* them to Local list (e.g. Apply button wich is only visible when something is selected)
- **2nd tab** shows Local items + Edit form
 - here items can be edited, selected/uselected & removed, or add new
 - tab's label indicates how much items are there which also gives feedback when Global tab is active.

Thoughts?

**Comment by assafharel** [comment] 2015-07-02 15:28
I don't think that tabs are the right design for it. These are not brothers.
We have a different suggestion that we think is better.
The list that we see now will become the local list.
Just like now it starts with 3 most popular criteria per topic.
Click on show more per item, pops up a modal window 
with the global list of items for the relevant topic. You can select whatever you want from that list, and click done. 
I know that you don't like, and I know that it's not mobile friendly, you may suggest different UI element that implements the behavior I'm suggesting.
I thought that in order to support mobile that window should be a small rectangle with scroll and search on top. No need for the show less button any more.
Regarding the search on top, it now searches through the global list. It will be nice if the list can be arranged per topic.
Let me know if you need me to wire-frame this suggestion.

**Comment by assafharel** [comment] 2015-07-02 15:31
Tal suggested moving the search to the right of the new, and make it smaller (half the table size, aligned to the right), as it's not as important as it is right now. You want to drive the attention of the user to the list.

**Comment by Pavek** [comment] 2015-07-02 17:35
Few comments:
> The list that we see now will become the local list. Just like now it starts with 3 most popular criteria per topic.

This is not clear. Local list is one that contains items copied/added to Project document, and initially it is *empty*, obviously. Global list is only has items initially. Please elaborate what do you mean by 'local list' here, and how it can contain 3 items initially.

Note: here, by 'items' I mean both products & requirements (criteria), becasue from selection point of view they are almost identical.

- Regarding Modal. I see you points, but actually don't see big difference beween tabs & modal, except that modal [has issues with mobile](http://uxmovement.com/mobile/why-you-should-avoid-using-modal-windows-on-mobile/). Usually, a solution for modal on mobile is to make the full-width (e.g. [this](http://jschr.github.io/bootstrap-modal/)), so essentailly your UI will look very similar to tabbed view, and difference is just switch between them by either [x] btn (modal) or by clicking other tab (tabs), imho. Well, modals may also have Cancel button which may be required (e.g. if it's a Question & Yes/No type of dialog), but this is not our case I belive and Cancel is not required.

**Comment by Pavek** [comment] 2015-07-02 17:44
Oh, and by 'tabbed' view I don't mean they should look like tabs on desktop, of course. I see this exmple to be tabbed too (a menu and not brothers):
http://gyazo.com/2579a577fb93775e595f1c23a1dffdd4

Essentially, out side-bar is tabs too, and could be styled e.g. like this (see .nav-stacked example):
http://getbootstrap.com/components/#nav-tabs

**Comment by assafharel** [comment] 2015-07-08 12:41
Tal just gave me another idea. Start with all topics closed, except one. Clicking on another topic, closes the first one, and opens the new one, etc. Only one topic is opened at a time.
That way, the full list is not in your face all the time, which is very exhausting to look at.
I can even think of a wizard like solution. The user answers to questions. "Do you have technology requirements"? If no, next topic, if yes, present few criteria per page, and let the user select what's yes and what's not.

Anyways, this is all become too complex, so start with the easiest / quickest full solution to the problem at hand. We will gather usability feedback to see if it needs improvements.

Assaf

**Comment by Pavek** [comment] 2015-07-09 16:36
So, this type of component is called [Accordion](http://getbootstrap.com/javascript/#collapse-example-accordion) -- a common alternatice to tabs. I agree that it reduces the complexity of the table.

Few comments:
- it is not clear how it fixes this issues -- filters. Does is mean filters should be removed?
- it doesn't solve issue #101 (show more/less, it refers to solution here) until filters are indeed removed
- it has conflict with group selection - I propose to remove group selection in favor of this control, as group selection has other negative effects.

**Comment by assafharel** [comment] 2015-07-10 10:49
OK, Start with Accordion and no filter, and we will see how it looks & feel (and reopen with more enhancements if required).
Don't forget that this issue also include a small fix: "Tal suggested moving the search to the right of the new, and make it smaller (half the table size, aligned to the right), as it's not as important as it is right now. You want to drive the attention of the user to the list".
I suggest doing the same for products as well (but not the accordion, as in products there's no 2-level nesting of items to select).

**Comment by Pavek** [comment] 2015-07-10 19:07
Implemented. Let me know if this is the right direction. If yes, please open new issues for new defects it  introduced.

**Comment by assafharel** [comment] 2015-07-12 09:34
Hi Pavel,

Re-opening for small fixes and tweaking. The implemantion itself is very good and looks much nicer then before. Good Job!
Fixes:
1. Please remove the priority mark from topics, and leave it only for Criteria.

2. Please remove the Show less / Show more buttons and always Show All. When we will have topics with dozens of criteria we will ask you to add an inner scroll (or you can do it right now, but right now it's not high priority, as the current max length is 17, I think, which is still manageable).
(This also solves issue #101, I believe...)

Thanks,
Assaf

**Comment by Pavek** [comment] 2015-07-12 15:48
By 'priority mark' do you mean popularity bar?

**Comment by assafharel** [comment] 2015-07-12 16:29
Yes
בתאריך Sun, Jul 12, 2015 ב-18:48 מאת Pavel Zhytko <notifications@github.com

**Closed** 2015-07-12 19:03 UTC
Labels: Priority: High
