### ISSUE TITLE
After signup close the page from the signup message

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#16] opened 2014-10-27 08:35 UTC
After a new signup, there is a message box referring to the confirmation email.
At the bottom of the message there is a note: "You can close this page now".
This text should be clickable and should close the page if clicked.

**Comment by Pavek** [comment] 2015-03-03 20:49
Closing pages from JavaScript is impossible by design (except popups). See this:
http://stackoverflow.com/questions/19761241/window-close-and-self-close-do-not-close-the-window-in-chrome

The solution should be on UX side, for example:
- show dialog on top of some form and allow to close it to reveal the form.
- or show a link to some public page: landing/blog/etc.

**Comment by assafharel** [comment] 2015-04-26 21:50
Please redirect the page to login page.

**Closed** 2015-04-28 01:39 UTC
