### ISSUE TITLE
Category-specific topics should appear at the beginning of the decision table

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#148] opened 2015-08-13 07:57 UTC
The category-specific topics (e.g. 'Contact & Call Center Functionality') should appear at the beginning of the decision table - like they appear in the Criteria page.

(Currently it is added last)

**Comment by Pavek** [comment] 2015-09-07 18:43
This is duplicate of #171 I believe and thus is fixed.

**Closed by Pavek** 2015-09-07 18:43 UTC
Labels: Priority: High
